import { Router } from 'express';
import authRoutes from './auth.js';
import inventoryRoutes from './inventory.js';
import analyticsRoutes from './analytics.js';
import customersRoutes from './customers.js';
import suppliersRoutes from './suppliers.js';
import dashboardRoutes from './dashboard.js';
import salesOrdersRoutes from './salesOrders.js';
import systemConfigRoutes from './systemConfig.routes.js';
import warehousesRoutes from './warehouses.routes.js';
import reportsRoutes from './reports.routes.js';
import accountingRoutes from './accounting.routes.js';
import paymentCollectionsRoutes from './paymentCollections.routes.js';
import activityLogsRoutes from './activityLogs.routes.js';
import notificationsRoutes from './notifications.routes.js';
import invoiceSettingsRoutes from './invoiceSettings.routes.js';
import taxConfigsRoutes from './taxConfigs.routes.js';
import stockTransfersRoutes from './stockTransfers.routes.js';
import stockRequestsRoutes from './stockRequests.routes.js';
import purchaseOrdersRoutes from './purchaseOrders.routes.js';
import salesRepsRoutes from './salesReps.routes.js';
import employeesRoutes from './employees.routes.js';
import branchesRoutes from './branches.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/customers', customersRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/sales-orders', salesOrdersRoutes);
router.use('/system-config', systemConfigRoutes);
router.use('/warehouses', warehousesRoutes);
router.use('/reports', reportsRoutes);
router.use('/accounting', accountingRoutes);
router.use('/activity-logs', activityLogsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/invoice-settings', invoiceSettingsRoutes);
router.use('/tax-configs', taxConfigsRoutes);
router.use('/stock-transfers', stockTransfersRoutes);
router.use('/stock-requests', stockRequestsRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);
router.use('/sales-reps', salesRepsRoutes);
router.use('/employees', employeesRoutes);
router.use('/branches', branchesRoutes);
router.use('/payment-collections', paymentCollectionsRoutes);

export default router;
